### ISSUE TITLE
Some features I would like

### ISSUE THREAD

**Issue by expez** [LearnProgramming/hamper#1]
#### Turn off URL shortening

Right now hamper is indiscriminately url-shortening everything.  For those of us with 
url-shortening built-in to our clients this is annoying, and sometimes the url shortening isn't needed.  I suggest we turn off url shortening by default.  And make the following addition to Hamper:

`!url` should return the shortened version of the last url to appear in chat.
#### Watch the LearnProgrammining repositories and make announcements on IRC

I think it would be cool if any activity in one of the organization's repositories on Github is announced on IRC.  Specifically I think Hamper should announce:
- Any commits
- Any pull-requests.
- Any new issues.

As the organization, and/or level of activitiy, grows we might have to review what we announce, but at present we'd only see a few announcements per week.

**Comment by Lbatson** [comment]
Both good ideas. I think we should also open these up as actionable issues for Hamper.

**Comment by chancez** [comment]
Git stuff is available directly through github, no bot action necessary. In fact its fairly trivial to set up.

As for the url shortening, thats something fairly easy to implement. If you want to add this feature, have at it. As a note, you can ignore the url shortening by using filters in your irc client.

**Comment by Lbatson** [comment]
I went through and set up service hooks for all the repos to notify the lpmc channel on pr, commits etc

**Comment by expez** [comment]
Awesome!
