### ISSUE TITLE
Help command

### ISSUE THREAD

**Issue by Lbatson** [LearnProgramming/hamper#6]
The help command currently responds using multiple messages instead of one longer message for information. This could and probably should be condensed to 1 message so as to not spam the channel. Removing the \n should be an easy fix.

**Comment by chancez** [comment]
This already exists as !plugins or !plugins list. We could change the default for the help command without args to ask the user for a plugin, and to suggest !plugin list if you need a list of commands.

@intothev01d what do you think?

**Comment by Lbatson** [comment]
Could do that yea. Also since the help file is really just description for plugins and use we could move it over to plugin_utils and have like a !plugin help which would tell you to use !plugin list to see the plugins and pick one and then call !plugin help {name of plugin} to get specifics.

**Comment by chancez** [comment]
I'd prefer to keep them seperate. The plugin_utils is purely to administer the plugins, like loading/reloading/unload (although a lot of that doesn't work now that Exocet is gone). There isn't any sort of permission system so the plugin_utils stuff generally gets unloaded, and thats why keeping help its own seperate thing is better IMO.

**Comment by Lbatson** [comment]
That makes sense. Then i guess if a user wanted to list them the !help without args should tell the user that they can call !plugins or !plugins list to see a list as well as it asking them to provide a specific plugin name for more info using? Then they would call !help {plugin name} to find out about how to use it.

Edit: Another thought might even be to have the !help without args just call the plugin list function and then explain they need to choose one and do !help {plugin name}.

**Comment by chancez** [comment]
Ideally plugins should be encapsulated and separated, so i think just having the help command's default only list the name of the plugin (and not the short desc) would be good.

**Comment by Lbatson** [comment]
Gotcha, so then it would be similar to what plugin list does just implemented over in the Help plugin. Basically list plugins and explain to find out details use !help {plugin name}
